### ISSUE TITLE
[Error] Steam workshop download fails

### ISSUE THREAD

**Issue by cicada3k301** [ArjixWasTaken/my-userscripts#1]
Hi there, first of all, thanks to share this amazing script.
But I've get a error message when I try to download this https://steamcommunity.com/sharedfiles/filedetails/?id=2808880923.
"No Download Link Found"

Can u help me please?

**Comment by ArjixWasTaken** [comment]
~~I am already working on a fix for this error along with batch download support.
So please be patient.~~

**Comment by ArjixWasTaken** [comment]
~~Try now with the latest version~~
Edit, this is not an issue with my script, rather it is an issue with the website that I am using to create the download link.
Therefore I will close this issue.
