### ISSUE TITLE
SteamWorkshop Downloader not working.

### ISSUE THREAD

**Issue by KAGEYAM4** [ArjixWasTaken/my-userscripts#5]
After clicking download button...
it keeps on showing - " Status: Fetching Download link" 
i am trying to download Wallpaper Engine workshop item its size is 1.8GB

**Comment by ArjixWasTaken** [comment]
I can't help if you don't give me all the info I need in order to look into this.
Like, what is the link to that workshop item?

And did you try on [steamworkshop.download](http://steamworkshop.download) before making this issue?
Does it download fine using [steamworkshop.download](http://steamworkshop.download)?

Answer all those questions and I might be able to help.

**Comment by KAGEYAM4** [comment]
> I can't help if you don't give me all the info I need in order to look into this. Like, what is the link to that workshop item?
> 
> And did you try on [steamworkshop.download](http://steamworkshop.download) before making this issue? Does it download fine using [steamworkshop.download](http://steamworkshop.download)?
> 
> Answer all those questions and I might be able to help.

here's the link not exactly to the same wallpaper , but i tried 5 items and none of them were able to download,
https://steamcommunity.com/sharedfiles/filedetails/?id=2813919164&searchtext=

also steamworkshop.download also stopped working, you try it too. it just says "Free space left", don' t know what that means.. 
is the script working for you. ?

**Comment by ArjixWasTaken** [comment]
this is what I get
![image](https://user-images.githubusercontent.com/53124886/172025624-7f12dacb-39c9-417c-88b6-f6a41234459f.png)

and it looks like it doesn't work on [steamworkshop.download](http://steamworkshop.download/), my userscript is just automating the process of downloading from [steamworkshop.download](http://steamworkshop.download/), if it doesnt work there, then it wont work with my userscript
