### ISSUE TITLE
Steam Workshop Tampermonkey script failing to find download link

### ISSUE THREAD

**Issue by Peesh98** [ArjixWasTaken/my-userscripts#6]
Hi, 

Thanks for making this script, it seems like it would make downloading workshop maps a whole lot easier.

However, I get this error when I press the download button:

![image](https://user-images.githubusercontent.com/105963680/172876959-10578446-533c-431e-8962-4fea83e0f87a.png)

I can use steamworkshop.download just fine to download it. The link is https://steamcommunity.com/sharedfiles/filedetails/?id=506206340&searchtext=surf if you want to try it for yourself. If you could provide some help regarding this I would appreciate it a lot.

**Comment by ArjixWasTaken** [comment]
update the userscript and try again

**Comment by Peesh98** [comment]
Thanks for the response!

I updated the userscript and now pressing the Download button downloads a .zip archive with the name of workshop item and its ID number in brackets. So in this case "Surf Master (506206340).zip". However, when trying to open the .zip archive using WinRAR, I get the following error: "The archive is either in unknown format or damaged".

**Comment by ArjixWasTaken** [comment]
huh

**Comment by ArjixWasTaken** [comment]
I think I have finally fixed it, please take a look.

**Comment by Peesh98** [comment]
Still having the same problem with the .zip file where I get the error "The archive is either in unknown format or damaged" unfortunately.

**Comment by ArjixWasTaken** [comment]
But it should not download an archive, it should download a .bsp file...

Are you sure you have updated to the latest version?

**Comment by Peesh98** [comment]
Yup, I double checked and it said I was on version 2.3. Is that correct?

**Comment by ArjixWasTaken** [comment]
Yes version 2.3 is the correct one.

https://user-images.githubusercontent.com/53124886/173255119-73e5e0b2-052d-4931-a6e4-22bb4f9d5e1d.mp4

But it works fine for me...

**Comment by ArjixWasTaken** [comment]
Please open the dev tools before you click the download button, then proceed to click the button and capture the entire output that the dev tools show, and finally paste that here.

Example below:

https://user-images.githubusercontent.com/53124886/173255375-2f7c7f87-9434-407e-9ebc-46c03a333486.mp4


The example above does not face any issue downloading the file, but it does not matter as you will do the same steps to share the error.

**Comment by Peesh98** [comment]
Hey! Sorry for replying so late! I was busy with some things in life. I've attached an image of the console output here:

![image](https://user-images.githubusercontent.com/105963680/176975535-84505b8a-bb97-4f73-87a0-657cb0376149.png)
