### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ImHereToReportIssues** [ArjixWasTaken/my-userscripts#7]
Hi, whenever I try to download it says failed to find download link.
I've tried it with other steam workshop items and it still doesn't work. Please help.
This is the mod: https://steamcommunity.com/sharedfiles/filedetails/?id=2211271581
![image](https://user-images.githubusercontent.com/107540446/173776397-6ceea105-0c7c-4914-92a6-665b54178521.png)

**Comment by djdoubt03** [comment]
When I click download, nothing downloads, and it does say "Status: Found download link"

**Comment by ArjixWasTaken** [comment]
https://github.com/ArjixWasTaken/my-userscripts#note
