### ISSUE TITLE
Doesn't work for some workshops

### ISSUE THREAD

**Issue by gaosen1** [ArjixWasTaken/my-userscripts#8]
This userscript is amazing! But sometimes it doesn't work.
When I download the latest workshop of WallpaperEngine, I get an error: ```Status: Failed to find download link.```
But when I downloaded the workshop from a few years ago, it did work.
I guess it may be that WallpaperEngine does some protection mechanism.

Browser console print information:
> 
```
{
    "method": "GET",
    "url": "http://steamworkshop.download/download/view/2870209872"
}
```
>
```
{
    "method": "POST",
    "data": "app=431960&item=2870209872",
    "headers": {
        "Content-Type": "application/x-www-form-urlencoded",
        "Host": "steamworkshop.download",
        "Origin": "http://steamworkshop.download",
        "Referer": "http://steamworkshop.download/download/view/2870209872"
    },
    "url": "http://steamworkshop.download/online/steamonline.php"
}
```
>
```No download link found for 2870209872```
>
![1](https://user-images.githubusercontent.com/75928758/194605208-7bf5ec45-494e-49de-bf3e-2dfbd1a77acb.png)
Please ignore the last warning,it's not relevant...

**Comment by ArjixWasTaken** [comment]
Lmao, this was still working? Wow

Anyways, valve AKA steam has changed how workshop downloads work, so the things you could download using my userscript are things that were previously cached by the website im using to download them.

Anything recent is not cached, therefore won't download.

So even if you can download an item, it might be out of date compared to the one on the workshop.

Sadly that's the truth, you need to own the game to freely download from the workshop.

**Comment by KAGEYAM4** [comment]
@ArjixWasTaken  you should update the readme , if not then people will still try to use it and waste there time and create a issue here later.

**Comment by ArjixWasTaken** [comment]
I guess I'll do just that.

**Comment by gaosen1** [comment]
All right.What a pity.

> Lmao, this was still working? Wow
> 
> Anyways, valve AKA steam has changed how workshop downloads work, so the things you could download using my userscript are things that were previously cached by the website im using to download them.
> 
> Anything recent is not cached, therefore won't download.
> 
> So even if you can download an item, it might be out of date compared to the one on the workshop.
> 
> Sadly that's the truth, you need to own the game to freely download from the workshop.
